use_frameworks!

platform :ios, '9.0'

target 'LJKit_Example' do
  
#  pod 'LJKit', :git => 'https://github.com/liujingCode/LJKit.git'

#  pod 'LJKit/Utils/HttpManager', :path => '../'

  pod 'YYModel'
  pod 'Masonry',:inhibit_warnings => true
  pod 'SDWebImage',:inhibit_warnings => true
  pod 'AFNetworking'
  pod 'MJRefresh',:inhibit_warnings => true
  pod 'MJExtension'
  pod 'IQKeyboardManager'
  pod 'SDCycleScrollView',:inhibit_warnings => true
  pod 'MBProgressHUD', '~> 1.1.0'
  
  pod 'TZImagePickerController'

  target 'LJKit_Tests' do
    inherit! :search_paths
  end
end
